version: '3'

services:
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  collatz:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy